name: Build Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt  # Ensure all dependencies are installed

      - name: Build executable
        run: |
          pyinstaller --clean --noconfirm Wall-You-Need.spec  # Build using the .spec file with --onefile option

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: wallpaper-updater
          path: dist/Wall-You-Need.exe  # Upload the single executable file