name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            ## v0.9.0 - First Release
            This is the first public release of the Wallpaper Updater program. 🎉

            ### Fixed:
            - ~~url isn't changing from GUI, until restart~~
            - ~~exe always showing returned non-zero exit status 1~~
            - ~~start with Windows not reflecting the correct state upon running the program~~
            - ~~.env being created from exe, still not decided whether to keep or remove from code~~
            - ~~couldn't delete being used by another process~~ (Added delay after setting new wallpaper)
            - ~~rarely failed to delete~~ (Terminated `depotdownloader` before deletion)
            - ~~check interval 30 changing to 300 not working~~ (Config updates now apply correctly)

            ### Known Issues:
            - Even when it's just a collection from people, it shows "fetching from page X" — fix this.
            - Wallpaper occasionally not set immediately after download; might require adding a delay.
            - Clicking the "X" button while `depotdownloader` runs still hangs the exe.
            - Remove logic for "last scrape time" created from exe.
            - Untested platforms: macOS, Linux.

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/Wall-You-Need.exe
          asset_name: Wall-You-Need.exe
          asset_content_type: application/octet-stream