name: Release Executable

on:
  push:
    tags:
      - 'v*'  # Trigger release when a version tag is pushed (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed gui.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: wallpaper-updater
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/wallpaper-updater.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
